# Generated by Django 4.1.2 on 2022-11-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('pic', models.ImageField(upload_to='')),
                ('pwd', models.CharField(max_length=15)),
            ],
        ),
    ]
